In [6]:
import numpy as np

In [7]:
#numpy array

In [8]:
my_list = [10,20,30,40]

In [9]:
type(my_list)

list

In [10]:
np.array(my_list)

array([10, 20, 30, 40])

In [11]:
my_numpy_array = np.array(my_list)

In [12]:
type(my_numpy_array)

numpy.ndarray

In [13]:
my_numpy_array

array([10, 20, 30, 40])

In [14]:
my_numpy_array[0]

np.int64(10)

In [17]:
my_numpy_array[-1]

np.int64(40)

In [18]:
my_numpy_array[0]=100

In [19]:
my_numpy_array

array([100,  20,  30,  40])

In [20]:
my_numpy_array.max()

np.int64(100)

In [22]:
my_numpy_array.min()

np.int64(20)

In [23]:
my_numpy_array.mean()

np.float64(47.5)

In [24]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [25]:
type(matrix_list)

list

In [26]:
matrix_list[0][0]

1

In [28]:
numpy_matrix_list = np.array(matrix_list)

In [29]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [30]:
numpy_matrix_list[0][0]

np.int64(1)

In [31]:
numpy_matrix_list.shape

(4, 3)

In [32]:
#arange

In [33]:
range (0,10)

range(0, 10)

In [34]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,40,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.ones((1,1))

array([[1.]])

In [41]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
#linspace

In [43]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [44]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [45]:
#random

In [47]:
np.random.randint(1,10,3)

array([4, 4, 3], dtype=int32)

In [48]:
np.random.randint(100)

99

In [49]:
np.random.randint(1,100,10)

array([14, 84,  4, 36,  9, 46, 93, 18, 54, 23], dtype=int32)

In [50]:
# numpy arrays methods

In [51]:
my_numpy_list = np.arange(0,20)

In [52]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
my_numpy_list[4]

np.int64(4)

In [55]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [56]:
my_list = list (range(0,20))

In [57]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [58]:
my_list[4:9] = -10

TypeError: can only assign an iterable

In [59]:
my_numpy_list[4:9] = -10

In [60]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [61]:
other_list = np.arange(0,15)

In [62]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [74]:
slicing_list = other_list[4:10]

In [75]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [76]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
slicing_list [:] = 100

In [80]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [81]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [82]:
#aynı listeye atamadık ama birbiriyle bağlantılı kalıyor

In [83]:
#böyle olmasını istemiyorsak copy methoduyla farklı liste oluşturuyoruz ve bağlantısı kalmıyor

In [85]:
numpy_list_3 = np.arange(0,20)

In [86]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
numpy_list_3_copy = numpy_list_3.copy()

In [88]:
slicing_3 = numpy_list_3_copy[4:9]

In [92]:
slicing_3[:] = 39

In [93]:
slicing_3

array([39, 39, 39, 39, 39])

In [94]:
numpy_list_3_copy

array([ 0,  1,  2,  3, 39, 39, 39, 39, 39,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [95]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [96]:
#numpy operations with numpy arrays

In [97]:
new_array = np.random.randint(1,150,25)

In [98]:
new_array

array([ 61,   3,  26, 137, 114,  75,   9,  68, 135, 140,  17, 126, 132,
        87, 147,  42, 101, 136, 146,  10, 148,  89,  92, 133, 131],
      dtype=int32)

In [99]:
new_array > 40

array([ True, False, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True])

In [100]:
result_array = new_array > 40

In [102]:
result_array

array([ True, False, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True])

In [104]:
new_array[result_array]

array([ 61, 137, 114,  75,  68, 135, 140, 126, 132,  87, 147,  42, 101,
       136, 146, 148,  89,  92, 133, 131], dtype=int32)